version: '2'
services:
    sale-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/sale/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=sale
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
